version: "3.7"
services: 
  db: 
    image: postgres
    ports: 
      "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  node: 
    build: .
    image: e_estate
    ports:
      - "3000:3005"
    depends_on:
      - postgres
    command: ["npm", "start"]
